---
- name: Docker Pull and Deploy
  hosts: deb
  ignore_unreachable: yes
  gather_facts: no
  become: yes

  tasks:
    # - name: Log into docker hub registry
    #   docker_login:
    #     email: "your-email@address"
    #     username: "a-dockerhub-username"
    #     password: "a-dockerhub-password"
    
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: beem.jfrog.io
        username: "gitauwairimu@gmail.com"
        email: "gitauwairimu@gmail.com"
        password: "cmVmdGtuOjAxOjE3MDUzNTk1NDE6N3NwR3ZEU3c1MkRIQlRQbGFHelYxMXZlYVFI"
        reauthorize: yes

    - name: Ensure the Application container is running
      docker_container:
        name: app_container
        state: started
        image: "beem.jfrog.io/docker-local/mavenenterprise:staging-20"
        pull: true
        ports:
          - "8080:8080"

