---
- name: Install Docker docker
  hosts: deb
  ignore_unreachable: yes
  gather_facts: no

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    ansible.builtin.apt:
    update_cache: yes

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
    become: true

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
    become: true