---
- name: Install Docker docker build and push
  hosts: deb
  ignore_unreachable: yes
  gather_facts: no

  tasks:
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
    become: true

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
    become: true

---
- name: Docker build and push
  hosts: deb
  ignore_unreachable: yes
  gather_facts: no

  vars:
    sourcefile: '/workspace/fasto/target/*.jar'
    source: '/workspace/fasto/target/*.jar'
    destination: '/home/vagrant/java_project'

  tasks:
  - name: Copy Files
    copy:
      src: /workspace/fasto
      dest: /home/vagrant/terrabkp.tar.gz

  - name: copy Git files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: '{{ destination }}'
      owner: devops
      mode: '0644'
    with_fileglob:
      - "examples/*.txt"


  - name: Copy jar file by synchronization 
    ansible.posix.synchronize:
      src: '{{ source }}'
      dest: '{{ destination }}'
    become: true  





# ssh into docker server
# execute a playbook that- 

# installs docker, 
# copies .tar file to the server, 
# builds an image, 
# push to dockerhub
# deploys it and 
# gives server/service status
